[package]
name = "vector"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
common.workspace = true
bytes.workspace = true
dashmap.workspace = true
fail.workspace = true
futures.workspace = true
usearch = "2"
roaring.workspace = true
rstest.workspace = true
tokio.workspace = true

[dev-dependencies]
rand = "0.8"
